### ISSUE TITLE
Cannot run tests via command line which have `group`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/scheduled_test#20]
```
#0      Expando._checkType (dart:core-patch/expando_patch.dart:134)
#1      Expando.[] (dart:core-patch/expando_patch.dart:14)
#2      _DeclarerProperty.value (package:scheduled_test/scheduled_test.dart:211:25)
#3      _initializeForGroup (package:scheduled_test/scheduled_test.dart:148:28)
#4      test (package:scheduled_test/scheduled_test.dart:63:3)
#5      main (file:///Users/kevmoo/source/github/shelf/test/shelf_io_test.dart:21:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by nex3** [comment]
Can you include an example of a test that fails?

**Comment by kevmoo** [comment]
``` dart
import 'package:scheduled_test/scheduled_test.dart';

void main() {
  group('hello', () {
    test('hi', () {
      expect(true, isTrue);
    });
  });
}
```
